apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: km2sds
nameSuffix: -geba1
namePrefix: dev-

commonLabels:
  app: superapi
  version: v1
  env: dev

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

resources:
#  - namespace.yaml
  - rollout.yaml
#  - service.yaml

configMapGenerator:
- name: superapi-config
  literals:
    - WELCOME=Hello from v2567324354
    - PORT=8080
