apiVersion: v1
kind: Service
metadata:
  name:  service
spec:
  ports:
    - protocol: tcp
      port:  35080
      targetPort: 35080
---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  ports:
    - protocol: tcp
      port:  35080
      targetPort: 35080
