kind: Service
apiVersion: v1
metadata:
  name:  superapi-svc-preview
spec:
  selector:
    app:  superapi
  type:  ClusterIP
#    type:  NodePort  
  ports:
  - name:  http
    port:  80
    targetPort:  8080
