apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blue-green
 
nameSuffix: -geba
namePrefix: dev-
 
commonLabels:
  app: superapi
  version: v1
  env: dev
 
 
configurations:
  - rollout-transform.yaml
 
resources:
  - namespace.yaml
  - rollout.yaml
  - service-active.yaml
  - service-preview.yaml
 
configMapGenerator:
- name: superapi-config
  literals:
    - WELCOME=Hello from v1!
    - PORT=8080   
