apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blue-green
 
nameSuffix: -geba
namePrefix: dev-
 
commonLabels:
  app: superapi
  version: v1
  env: dev
 
 
configurations:
  - rollout-transform.yaml
 
resources:
# base Argo CD components
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/ha/install.yaml
  - namespace.yaml
  - rollout.yaml
  - service-active.yaml
  - service-preview.yaml

components:
# extensions controller component
- https://github.com/argoproj-labs/argocd-extensions/manifests

configMapGenerator:
- name: superapi-config
  literals:
    - WELCOME=Hello from v1!
    - PORT=8080   
