apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout
spec:
  strategy:
    blueGreen:
      activeService: servie
      previewService: green
      autoPromotionEnabled: false
  replicas: 2
  revisionhistorylimit: 2
  selector:
    matchLabels:
      app: superapi
  template:
    metadata:
      labels:
        app: superapi
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: overlay
      containers:
      - name: main
        image: ghcr.io/gbaeke/super:1.0.2
        imagePullPolicy: Always 
        resources:
          requests:
            memory: "1024Mi"
            cpu: "50m"
          limits:
            memory: "1024Mi"
            cpu: "50m"
        env:
          - name: WELCOME
            valueFrom:
              configMapKeyRef:
                name: superapi-config
                key: WELCOME
        ports:
        - containerPort: 8080
