apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout
spec:
  strategy:
    blueGreen:
      activeService: servie
      previewService: green
      autoPromotionEnabled: false
  replicas: 2
  revisionhistorylimit: 2
  selector:
    matchLabels:
      app: superapi
  template:
    metadata:
      labels:
        app: superapi
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: overlay
     containers:
      
      - name: main
        image: ghcr.io/gbaeke/super:1.0.2
        imagePullPolicy: Always 
        resources:
          requests:
            memory: "1024Mi"
            cpu: "50m"
          limits:
            memory: "1024Mi"
            cpu: "50m"
        env:
          - name: WELCOME
            valueFrom:
              configMapKeyRef:
                name: superapi-config
                key: WELCOME
        livenessProbe:
          httpGet:
            path: /emm/admin/login.do
            port: 35080
          initialDelaySeconds: 30
          periodSeconds: 30
        command: ["/bin/sh","-c"]
        arg: ["/data/apache-tomcat/bin/catalina.sh run"]
        envFrom:
          - configMapRef:
              name: cm
          - secretRef:
              name: db-secret
        env:
        - name: POD_NAME
          valueFrom:
             filedRef:
                fieldPath: metadata.name
         - name:NODE_NAME
           valueFrom:
              fieldPath: spec.nodeName
         - name: LOG_PATH
           value: /data/logs/app/$(SERVICE)/$(POD_NAME)
           
        ports:
        - containerPort: 8080
